from typing import Callable, List, Tuple, Dict, Any
from clobber.types import piece_type, move


class Board:
    n: int
    m: int
    turn: int
    state: List[str]

    def __init__(self, n: int, m: int,
                 state: List[str], turn: int = 0) -> None: ...

    @staticmethod
    def initialize_board(
        n: int, m: int) -> 'Board': ...

    def copy(self) -> 'Board': ...

    def __str__(self) -> str: ...
    def pretty(self) -> str: ...

    def get_piece_at(self, position: Tuple[int, int]) -> piece_type: ...

    def replace_piece_at(
        self, position: Tuple[int, int], new_piece: piece_type) -> piece_type: ...

    def get_neighbours_positions(
        self, position: Tuple[int, int]) -> List[Tuple[int, int]]: ...
    def get_neighbours_positions_filtered(self, position: Tuple[int, int], piece_filter: Callable[[
                                          piece_type], bool]) -> List[Tuple[int, int]]: ...

    def make_move(self, new_color: piece_type, m: move) -> None: ...
    def move_assuming_correct(
        self, new_color: piece_type, m: move) -> None: ...

    def get_all_pieces(self, piece: piece_type) -> List[Tuple[int, int]]: ...
    def generate_moves(
        self, for_white: bool) -> Dict[Tuple[int, int], List[Tuple[int, int]]]: ...

    def has_moves(self, white: bool) -> bool: ...
